### PR TITLE
recognize START WITH 0 option for IDENTITY 

### PR DESCRIPTION
**Pull request by rusabd**
related to issue #102

### CODE REVIEW

**Comment by TallTed** [comment]
@imitko -- Please act on this PR before it reaches another anniversary. 

/cc @openlink @pkleef

**Comment by rusabd1** [comment]
8 years! I don't even remember what this ticket is about, guys :)

**Comment by rusabd** [comment]
8 years! I don't even remember what this ticket is about, guys :)

**Comment by imitko** [comment]
Already fixed with patch e07fa5bcea114c52a5ca6f0d062d38a792ae4f5d

**Pull request closed without merging**
